[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hh_neos"
version = "0.1"
requires-python = ">=3.9"
dependencies = [
    "sklearn",
    "scikit-learn==1.1.1",
    "chex==0.1.3",
    "jax==0.3.14",
    "jaxlib==0.3.14",
    "optax==0.1.2",
    "plothelp==0.1",
    "equinox==0.5.5",
    "pyhf @ git+https://github.com/scikit-hep/pyhf.git@make_difffable_model_ctor",
    "relaxed @ git+https://github.com/fred-renner/relaxed.git@mle_fix",
    "neos==0.3.0",
    "jupyter",
    "h5py",
]

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[project.scripts]
hh_neos = "hh_neos.main:run"
hh_neos_plot = "hh_neos.main:plot"
